### PR TITLE
feat(#3114): Improve pipeline details view

### PR DESCRIPTION
**Pull request by dominikriemer**
### Purpose

See #3114 
### Remarks

PR introduces (a) breaking change(s): no

PR introduces (a) deprecation(s): no

### CODE REVIEW

**Comment by tenthe** [comment]
`pipeline-details.routes.ts` seems not to be used anywhere. Can it be deleted?

**Comment by tenthe** [comment]
I tried the "Refresh metrics" button, but the metrics were not updated.
How often are the metrics updated? The "Auto refresh" button triggers the "/metrics" endpoint, but the values don't change often.
From a user's perspective, this could be unexpected, what do you think?

grafik

**Review by tenthe — COMMENTED** [review]
Thanks for the PR. I really like the refactoring.
I added some minor comments to discuss.

**Review by tenthe — APPROVED** [review]

**Comment by dominikriemer** [comment]
Thanks Philipp for your feedback.
I plan two push two more PRs related to the pipeline view (cleanup of the editor components and preview in the details view), I'll address your comments in these two PRs.

**Pull request merged**
