### PR TITLE
Migrate boolean counter #1366

### PR DESCRIPTION
**Pull request by flaxxen**
### Purpose
Migrate the boolean counter processor element to a single class structure.

Fixes issue #1366

### Remarks
A few test cases added to make sure functionallity is as expected. Since this module did not have any tests before we're not sure what you'd think about that but let me know if you want them in the PR or not.

PR introduces (a) breaking change(s): no
PR introduces (a) deprecation(s): no (?)

### CODE REVIEW

**Comment by bossenti** [comment]
@flaxxen really awesome that you even provided tests 🤩
Tests are often neglected in our cosebase, we really need to improve here... 
thanks a lot for providing this pr 🙏 I'll have a detailed look on it later on

**Comment by flaxxen** [comment]
Great! No worries, let me know if you want anything changed. :)

**Review by dominikriemer — APPROVED** [review]

**Comment by dominikriemer** [comment]
Very cool, thank you @flaxxen!

**Review by bossenti — APPROVED** [review]

**Comment by bossenti** [comment]
Great work from your team @flaxxen!

**Comment by bossenti** [comment]
@flaxxen 
Since you mentioned that you are working on a school project, [GSOC](https://summerofcode.withgoogle.com/) might be of interest to you and your team.
This is a project offered by Google to get people excited about open source contributions.
We also offer [some challenges](https://github.com/apache/streampipes/labels/gsoc), but there are also a [lot of other interesting proposals](https://cwiki.apache.org/confluence/display/COMDEV/GSoC+2023+Ideas+list) from across the range of Apache projects. Additionally, you can always come up with your own ideas 💡 
Just as a pointer 🙂

**Comment by flaxxen** [comment]
@bossenti Oh, that's really cool. Thx for the idea, never heard about it before. I'll let my team know as well and see if any one is interested. :)

**Comment by bossenti** [comment]
Feel free to approach us if you have any question

**Pull request merged**
