### PR TITLE
refactor(#2092): Use HttpStatus in stead of plain strings

### PR DESCRIPTION
**Pull request by bagechengzi**
…the corresponding values of code.HttpStatus

  
  

### Purpose

Remove occurrences of hard-coded HTTP results and replace them with the corresponding values of HttpStatus code.

### Remarks

PR introduces (a) breaking change(s): no

PR introduces (a) deprecation(s): no

### CODE REVIEW

**Comment by bagechengzi** [comment]
#2092

**Review by dominikriemer — APPROVED** [review]
Thanks a lot @bagechengzi !

**Comment by tenthe** [comment]
Hi @bagechengzi,
thanks for providing this PR.
There are a few checkstyle violations that caused the PR validation to fail.
```
Error:  src/main/java/org/apache/streampipes/client/api/AbstractTypedClientApi.java:[21,1] (imports) ImportOrder: Import org.apache.streampipes.client.http.GetRequest appears after other imports that it should precede
Error:  src/main/java/org/apache/streampipes/client/api/AbstractClientApi.java:[21,1] (imports) ImportOrder: Import org.apache.streampipes.client.http.DeleteRequest appears after other imports that it should precede
Error:  src/main/java/org/apache/streampipes/client/http/HttpRequest.java:[109] (sizes) LineLength: Line is longer than 120 characters (found 124).
```

Once they are resolved, we can merge the PR.

Cheers,
Philipp

**Comment by bagechengzi** [comment]
resolved them

**Comment by bagechengzi** [comment]
Sorry, I'm not proficient in this

**Comment by bagechengzi** [comment]
Could someone tell me why it failed

**Review by tenthe — APPROVED** [review]

**Review by bossenti — APPROVED** [review]

**Pull request merged**
