### PR TITLE
#2144 Enhance Static Properties by UI validation

### PR DESCRIPTION
**Pull request by IsaakKrut**
Updated port number fields to Integer type for following adapters:
Ros Bridge
OPC UA
PLC4X MODBUS

Remarks
PR introduces (a) breaking change(s): no

PR introduces (a) deprecation(s): no

### CODE REVIEW

**Comment by tenthe** [comment]
Hi @IsaakKrut,
thanks a lot for submitting this pull request. I think this is a great improvement for users.

I was wondering if this change might require a migration script, as it will affect existing adapters during system upgrades.

Therefore, I would recommend providing an update script for the affected adapters. An example can be found in [1]. This change affected the PLC4X S7 adapter, where an alternative static property was added.

In general, the update script should ensure that the changes are correctly propagated to the user configurations of the existing adapter instances. In your case, the `requiredDatatype` of the `FreeTextStaticProperty` must be changed from `Datatypes.String` to `Datatypes.Integer` within the update script.

If you have any questions or need help with the implementation, please feel free to ask.

[1] https://github.com/apache/streampipes/blob/dev/streampipes-extensions/streampipes-connectors-plc/src/main/java/org/apache/streampipes/extensions/connectors/plc/adapter/migration/Plc4xS7AdapterMigrationV1.java

**Comment by IsaakKrut** [comment]
@tenthe Added the migration scripts. I was not able to test it locally, is there a way to set up different adapters for testing?

**Comment by tenthe** [comment]
Thank you for providing the migrations.
Unfortunately, I do not currently have a setup to test them locally. 

However, we  need a way to test such migrations. Perhaps we can create unit tests for this? What do you think? 
To test it e2e you would have to setup a system with the old version, update the system to the new dev version and check if it worked. But I am not sure how we could automate this.

At least I have added the label migration for the PR. Maybe we can use this in the future to label all PRs that contain a migration to test them again before the release.

**Comment by IsaakKrut** [comment]
I added a sample unit test for one of the migrations, let me know what you think. Maybe this approach becomes more messy for elements with larger configurations as it all has to be moved to those static methods

**Review by dominikriemer — APPROVED** [review]

**Comment by tenthe** [comment]
Many thanks for the PR @IsaakKrut.
Sorry for the late reply.

The test looks good.
@dominikriemer I was wondering what happens to the existing user input during configuration.
The same migration is used for both, the description of the processing elements and for the instances, right?

So I guess we need to check if a value is set in the original `StaticProperty` and set it for the new `StaticProperty` as well.
For the `RosBridgeAdapterMigrationV1` this would mean that we add the 'original' value to the `FreeTextStaticProperty` created in line 52.

Cheers,
Philipp

**Comment by tenthe** [comment]
Hi @IsaakKrut,

I have resolved the concerns regarding the values of the static properties for the OPC UA Adapter. Therefore, I have included these updates in pull request #2443.

Please review these changes and make appropriate adjustments to the remaining adapters.
Do the changes work from your point of view?

Cheers,
Philipp

**Pull request closed without merging**
