### PR TITLE
[#1146] Session based implementation of IoTDB sink (fix issues in current JDBC based implementation)

### PR DESCRIPTION
**Pull request by SteveYurongSu**
### Purpose

Recently, I was trying to play around streampipes and found that iotdb sink could not work properly.

I checked the source code and found that the current JDBC based implementation of iotdb sink is outdated, especially for the current production versions of iotdb (0.13.x and 1.0.x).

I‘d like to contribute a brand new iotdb sink implementation, which has the following features:

- Support production ready versions of IoTDB (version >= 0.13.0)
- Support by iotdb-session API, which can provide higher throughput and lower latency
- Support schema-less write: no need to create storage group (database) before insertion

See #1146 for more detail :D

### Remarks

PR introduces (a) breaking change(s): no

PR introduces (a) deprecation(s): yes
Old versions (< v0.13) of IoTDB are no longer supported.

### Tests
I setup a pipeline as the following:
image

Then I checked the data that IoTDB received:
image
image

### CODE REVIEW

**Comment by bossenti** [comment]
@SteveYurongSu Thank you so much for this awesome contribution 🙏🏼

**Comment by tenthe** [comment]
Hi @SteveYurongSu, thank you so much for this PR and updating the IoTDB implementation.

I have a question regarding the "session". 
The session is created in the `onInvocation` and closed in the `onDetach` and what happens if the connection dies during the execution of the pipeline. Would it be possible to add a reconnection in the `onEvent` for this case or is this not necessary? 
Maybe this can be done when the "IoTDBConnectionException" occurs.

**Comment by SteveYurongSu** [comment]
Hi @tenthe, thanks a lot for your reviewing. 

IoTDB has a native mechanism to handle the case that the connection dies. I will update the PR with the mechanism ASAP :-)

> Hi @SteveYurongSu, thank you so much for this PR and updating the IoTDB implementation.
> I tried it locally and everything worked fine. Thanks for updating the IoTDB version in the CLI.
> 
> I have a question regarding the "session". 
> The session is created in the `onInvocation` and closed in the `onDetach` and what happens if the connection dies during the execution of the pipeline. Would it be possible to add a reconnection in the `onEvent` for this case or is this not necessary? 
> Maybe this can be done when the "IoTDBConnectionException" occurs. 
>

**Comment by tenthe** [comment]
Awsome, thanks a lot. 
I am excited to see how this will be implemented by IoTDB

**Comment by SteveYurongSu** [comment]
Hi @bossenti, here is the update 😊

In streampipes-extensions/streampipes-sinks-databases-jvm/src/main/java/org/apache/streampipes/sinks/databases/jvm/iotdb/IotDb.java

I implemented the IoTDB sink by `SessionPool` instead of `Session`.

About `SessionPool`:
> We provide a connection pool (`SessionPool) for Native API. Using the interface, you need to define the pool size.
> 
> If you can not get a session connection in 60 seconds, there is a warning log but the program will hang.
> 
> If a session has finished an operation, it will be put back to the pool automatically. **If a session connection is broken, the session will be removed automatically and the pool will try to create a new session and redo the operation.**

**Review by tenthe — APPROVED** [review]

**Review by dominikriemer — APPROVED** [review]

**Comment by dominikriemer** [comment]
Thank you @SteveYurongSu !

**Comment by tenthe** [comment]
@SteveYurongSu thanks a lot for the super fast update.
I really like the new implementation

**Pull request merged**
