### PR TITLE
Feature/streampipes 627

### PR DESCRIPTION
**Pull request by bossenti**
### Purpose

Integrate style and codecheks as well as unit tests to our CI (pr-validation).

### Remarks

Fixes: [STREAMPIPES-627](https://issues.apache.org/jira/browse/STREAMPIPES-627)

### CODE REVIEW

**Comment by tenthe** [comment]
Hi Tim,
the PR looks good.
One general question, do you already know how long the code validation checks will run?
If this is rather fast, we could run all code validation first, then run the unit tests and finally run the e2e tests.
What do you think?

**Review by dominikriemer — APPROVED** [review]

**Comment by bossenti** [comment]
@tenthe `python-quality-check` took one minute and `unit-tests` between 30 und 60 seconds.
Currently, all jobs that are part of `pr-validation` run in parallel. So what would you change? I didn't get your suggestion, I'm afraid.

**Comment by tenthe** [comment]
ok great. 
The `run-cypress-e2e-tests` takes about 30 minutes. 
My question basically was if we should wait for all the code validations to pass before triggering the e2e tests?

**Comment by bossenti** [comment]
Indeed, thats a good one.
I'll adapt the workflow correspondingly.

**Comment by bossenti** [comment]
@tenthe Jobs run now sequentially, see: https://github.com/apache/streampipes/actions/runs/3499092709

**Pull request merged**
