### PR TITLE
Refactor Image Processors

### LINKED ISSUE #1330: Image Enricher

### PR DESCRIPTION
**Pull request by BudhirajaChinmay**
### Purpose

Fixes #1330 

### Remarks

PR introduces (a) breaking change(s): yes

PR introduces (a) deprecation(s): yes

### CODE REVIEW

**Comment by bossenti** [comment]
@BudhirajaChinmay I don't want to disturb you and your PR is still WIP, but I just want to mention shortly that there is no need to duplicate the processors to kee the old and new versions parallely. You can simply refactor the existing ones :) In general, this should not influence the actual behavior of the processing element since it's just a question of structuring the code.
In case that was anyways your plan, I didn't say anything 🙂

**Comment by BudhirajaChinmay** [comment]
@bossenti I thought of keeping the old and new both, using depricated for old processors. Will keep your comment in mind whilst working on it. Thanks for the input :D

**Comment by bossenti** [comment]
That's a noble aim but this will just result in too many pipeline elements. Furthermore, they don't differ in terms of functionality. It would create a lot of confusion when we have duplicates of all pipeline elements. In short, it would be great if you refrain from it 🙂

**Comment by BudhirajaChinmay** [comment]
Fixed the checkstyle errors.

**Comment by tenthe** [comment]
Hey @BudhirajaChinmay,
thanks a lot for the PR 🚀 it looks very good.
I have a small comment, can you please change the suffix of the classes from `Controler` to `Processor`.
This will make it directly clear for other developers that the processor is using the new API.

**Review by bossenti — APPROVED** [review]
@BudhirajaChinmay thanks a lot for this contribution 🙏🏼 
I really like your refactoring 👍🏼

**Review by tenthe — APPROVED** [review]

**Pull request merged**
