### PR TITLE
refactor(#2095): remove update button & move permissions button

### PR DESCRIPTION
**Pull request by bossenti**
### Purpose

see #2095 

One pipeline element is displayed the following now:
image

### Remarks

PR introduces (a) breaking change(s): no

PR introduces (a) deprecation(s): no

### CODE REVIEW

**Comment by dominikriemer** [comment]
@bossenti one question, how will development work without the update button?
E.g., when I develop a pipeline element, I often modify configs and test them by using the update button. Will this still work with the new approach or would I need to increase the version with every change?

**Comment by bossenti** [comment]
We do overwrite all adapter & pipeline element descriptions when starting an extensions service right? 
If so, there should be no need to manually update the descriptions during development. Or am I mistaken?

**Comment by tenthe** [comment]
@bossenti I'm not entirely certain if this is already the case, but I agree with you on how it should be.

**Review by tenthe — APPROVED** [review]

**Comment by bossenti** [comment]
I'll give it a final check before merging

**Comment by bossenti** [comment]
Which one do we want to take?

**Comment by dominikriemer** [comment]
I'd prefer to keep the manual update button for now.
But I like the `Manage Permissions` button ;-)

**Comment by bossenti** [comment]
Okay, fine for me 
Me too, but there is no space for three buttons right?

**Pull request closed without merging**
