### PR TITLE
[#877] Format and lint CustomMaterial module

### PR DESCRIPTION
**Pull request by aamirxshaikh**
### Purpose

Applying UI linting and formatting to the `CustomMaterial` module. Removing the `CustomMaterial` module from `ui/.eslintignore` and `ui/.prettierignore` and fixing formatting.

### CODE REVIEW

**Review by tenthe — APPROVED** [review]

**Comment by bossenti** [comment]
Do we want to rename the module to `custom-material` @tenthe @dominikriemer? Would be consistent with the other module names

**Comment by tenthe** [comment]
Yes, I think that is a good idea. 
We should also discuss if we still need this module. We should address the question whether it is good practice to make all dependencies into one module which is then imported by all others or if it is better to import the material modules directly.

**Comment by bossenti** [comment]
👍🏼 
But that's a follow-up topic right? 🙂

**Comment by tenthe** [comment]
Yes, that is a follow up topic

**Pull request merged**
