### PR TITLE
[#1936] Adapter Deletion: Disallow Deletion of Pipelines Using Adapter but Not Owned by User

### PR DESCRIPTION
**Pull request by muyangye**
### Purpose

See #1936 

### Remarks

PR introduces (a) breaking change(s): no

PR introduces (a) deprecation(s): no

### CODE REVIEW

**Comment by muyangye** [comment]
Currently, even admin can't delete pipelines created by others because I am comparing the id of pipeline's owner with the id of the user. Let me know if admin should delete pipelines not owned by himself.

**Comment by dominikriemer** [comment]
Hi @muyangye great that you're working on this topic!
Yes, I think admin users should always be able to delete resources owned by others.

**Comment by muyangye** [comment]
> Hi @muyangye great that you're working on this topic!
> Yes, I think admin users should always be able to delete resources owned by others.

Can they also delete resources owned by another admin?

**Comment by tenthe** [comment]
Hello @muyangye,
thanks for your work on this topic. 
In my opinion, it makes perfect sense for an admin to have the right to delete all resources, even if they were created by another admin.

**Comment by muyangye** [comment]
@dominikriemer @tenthe, thanks for clarifying! Just pushed an update that addressed this.

**Review by tenthe — APPROVED** [review]
@muyangye, thanks a lot for the PR.
The feature looks good

**Review by dominikriemer — APPROVED** [review]

**Pull request merged**
