### PR TITLE
Add checkstyle to missing modules

### PR DESCRIPTION
**Pull request by bossenti**
### Purpose

Add checkstyle configuration to the last remaining modules 🎉 

### Remarks

PR introduces (a) breaking change(s): no

PR introduces (a) deprecation(s): no

### CODE REVIEW

**Comment by tenthe** [comment]
🎉 very cool @bossenti, awsome work!
I also added an issue #880 to add the checkstyle validation as a git pre-commit hook.

**Comment by bossenti** [comment]
@tenthe how do you think about all the checkstyle errors in the `target` directory of `streampipes-maven-plugin`?
Should we simply ignore them?

**Comment by tenthe** [comment]
Good point, I would ignore them. 
Do you know how to do it? I couldn't figure out how to add it to the `supressions.xml`

**Comment by bossenti** [comment]
Hmm, that's how I would have done it, I'll give it a try.

**Comment by bossenti** [comment]
Should go through now :)

**Review by tenthe — APPROVED** [review]

**Pull request merged**
