### PR TITLE
[#805] create custom release notes configuration

### PR DESCRIPTION
**Pull request by bossenti**
### Purpose

Create config file for custom release notes automatically created by GitHub

### Remarks

Fixes: #805

### CODE REVIEW

**Comment by bossenti** [comment]
See an example in my private streampipes repository: https://github.com/bossenti/incubator-streampipes/releases/tag/release-demo

**Comment by bossenti** [comment]
One problem with this solution is that all issues/PRs related to the release tag are taken into account. This means that we would currently consider changes that relate to a future release but have already been merged. Can we live with that?

**Comment by tenthe** [comment]
Is it possible to manually edit the release notes after they were automatically created?

**Comment by bossenti** [comment]
Yes it is.
They are simly inserted into the release form you are about to create and you can modify them how ever you like.

**Comment by tenthe** [comment]
Fine, but then we can remove it manually if we don't want a change to become part of the release. 
And since these features are not yet fully completed, we will see them in changes in the next release.

**Review by dominikriemer — APPROVED** [review]

**Pull request merged**
