### PR TITLE
STREAMPIPES-644: Upgrade Flink version to latest 1.16

### PR DESCRIPTION
**Pull request by vesense**
### Purpose

Upgrade Flink version to latest 1.16

### Remarks

Fixes: <Jira issue link>
https://issues.apache.org/jira/browse/STREAMPIPES-644

### CODE REVIEW

**Comment by bossenti** [comment]
@vesense could you please have a look on the failed build?
https://github.com/apache/streampipes/actions/runs/3522766888/jobs/5906126439#step:4:91323

**Comment by vesense** [comment]
@bossenti Thanks for reminding. It is successfully to build in my local environment. I'll check it later.

**Comment by bossenti** [comment]
I'm afraid that this upgrade is not possible due to our usage of `flinkspector` for unit tests.
Flinkspector only supports flink <= 1.14 (if I'm not mistaken) and hasn't published a release since 2019.
So we probably need to look for an alternative, any ideas @tenthe @dominikriemer @vesense @RobertIndie?

**Comment by tenthe** [comment]
@bossenti I removed `flinkspector` in #1027

**Comment by bossenti** [comment]
@tenthe thanks, then we can update this PR and merge it I guess

**Comment by bossenti** [comment]
@dependabot rebase

**Comment by vesense** [comment]
Sorry for the delay response. Thanks @tenthe for your update https://github.com/apache/streampipes/pull/1027.
I merged the  https://github.com/apache/streampipes/pull/1027 into flink_1.16, the error was the same as in the before.
I checked the build logs*(1) and found the reason: When build `streampipes-processors-aggregation-flink`, maven uses the pom*(2) from remote apache central repo not local. That is to say, the remote pom is not the latest version. 
Maybe this is a bug, @tenthe @bossenti Could you take a look?

*1:
https://github.com/apache/streampipes/actions/runs/3865100468/jobs/6588382054#step:4:76696
key part:
>[INFO] --- maven-remote-resources-plugin:1.7.0:process (process-resource-bundles) @ streampipes-processors-aggregation-flink ---
[INFO] Preparing remote bundle org.apache:apache-jar-resource-bundle:1.4
[INFO] Copying 3 resources from 1 bundle.
Downloading from apache.snapshots: https://repository.apache.org/snapshots/org/apache/streampipes/streampipes-wrapper-flink/0.91.0-SNAPSHOT/streampipes-wrapper-flink-0.91.0-20230107.223648-27.pom

*2:
https://repository.apache.org/snapshots/org/apache/streampipes/streampipes-wrapper-flink/0.91.0-SNAPSHOT/streampipes-wrapper-flink-0.91.0-20230107.223648-27.pom

**Comment by tenthe** [comment]
Hi @vesense,
I tried to resolve the issues locally, but I've ran into similar problems.
I suspect that the problem is with the Flink version update, some of the other dependencies related to Flink also need to be changed. We should check them one by one to see if they are still required for this Flink version or if there are alternatives that need to be used.

**Comment by vesense** [comment]
@tenthe Thanks for your feedback, let me have a deep check.

**Pull request closed without merging**
