### PR TITLE
[#1088] Fix linkt to StreamPipes logo in Mkdocs

### PR DESCRIPTION
**Pull request by parthsali**

### CODE REVIEW

**Comment by bossenti** [comment]
@parthsali welcome to Apache StreamPipes and thank you for providing your first PR 🎉 
Could you please use the `raw` link to this image (https://raw.githubusercontent.com/apache/streampipes/dev/ui/deployment/dev/img/logo-navigation.png)? 
That would be great 🙏🏼

**Comment by parthsali** [comment]
> @parthsali welcome to Apache StreamPipes and thank you for providing your first PR 🎉 Could you please use the `raw` link to this image (https://raw.githubusercontent.com/apache/streampipes/dev/ui/deployment/dev/img/logo-navigation.png)? That would be great 🙏🏼

Sure👍

**Comment by parthsali** [comment]
I have updated the link for the logo in the docs. Could you please check it?

**Review by bossenti — APPROVED** [review]

**Comment by tenthe** [comment]
@parthsali welcome to StreamPipes.
Thanks a lot for your PR!

**Pull request merged**
