### PR TITLE
[STREAMPIPES-880] - checkstyle pre-commit hook installed

### PR DESCRIPTION
**Pull request by deexidee**
### Purpose

- [ ] include setup into development documentation

### Remarks

PR introduces (a) breaking change(s): no

PR introduces (a) deprecation(s): no

### CODE REVIEW

**Review by tenthe — APPROVED** [review]

**Comment by bossenti** [comment]
When I execute `pre-commit run` the following error occurs:
```
 failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:4b6abae565492dbe9e7a894137c966a7485154238902f2f25e9dbd9784383d81: not found
```
Am I the only one?
I'm on a M1 with Ventura `13.2.1`

**Comment by bossenti** [comment]
>  include setup into development documentation

Added as a reminder for us, you don't need to care about it @deexidee

**Comment by deexidee** [comment]
> When I execute `pre-commit run` the following error occurs:
> 
> ```
>  failed to solve with frontend dockerfile.v0: failed to create LLB definition: no match for platform in manifest sha256:4b6abae565492dbe9e7a894137c966a7485154238902f2f25e9dbd9784383d81: not found
> ```
> 
> Am I the only one? I'm on a M1 with Ventura `13.2.1`

didn't face it. I'm on Windows

**Comment by bossenti** [comment]
I couldn't test it entirely but I think that only one config file for `pre-commit` is possible in a git repository ( see https://github.com/pre-commit/pre-commit/issues/731 and https://github.com/pre-commit/pre-commit/issues/1203)
Accordingly, we would need to merge this one with the one used in `streampipes-client-python`

**Review by bossenti — CHANGES_REQUESTED** [review]
see above

**Comment by bossenti** [comment]
We could also determine which config to use by passing the `-c` parameter but this does only work one `pre-commit` is executed specifically and not as a git hook
So we probably need to spend some thoughts on our setup here

**Pull request closed without merging**
