### PR TITLE
guessSchema the encrypted secretValue should be decrypted when used

### PR DESCRIPTION
**Pull request by yanfeng1992**
### Purpose

The encrypted secretValue should be decrypted when used

### Remarks

PR introduces (a) breaking change(s): <yes/no>
no
PR introduces (a) deprecation(s): <yes/no>
no

### CODE REVIEW

**Comment by dominikriemer** [comment]
Hi @yanfeng1992 did you have any problem with the current setup?
Secrets should be decrypted by the core before they are sent to the extension service (to avoid that the extensions need to be aware of the encryption passcode) so that no decryption should be necessary when extracting a secret value.

**Comment by yanfeng1992** [comment]
I discovered that the current secret was not decrypted by the core before being sent to the extension service, and the extension service still received the encrypted password. @dominikriemer

**Comment by yanfeng1992** [comment]
I discovered it when adapting and modifying the configuration. Can it be fixed in core? I haven't found a way to fix it in core. 
Is it possible to add the decryption fix directly to the core?

**Comment by dominikriemer** [comment]
Hi @yanfeng1992 thanks for asking!
For pipeline elements, decryption is handled in `streampipes-pipeline-management` in the `SecretEncryptionTask`, which calls a `SecretService` that loops over all configuration and decrypts secrets. For adapters, this class is used within the `WorkerRestClient` of `streampipes-connect-management`. In which cases did you experience the problem? Does this occur always or only for nested structures or something like that?

**Comment by yanfeng1992** [comment]
> Hi @yanfeng1992 thanks for asking! For pipeline elements, decryption is handled in `streampipes-pipeline-management` in the `SecretEncryptionTask`, which calls a `SecretService` that loops over all configuration and decrypts secrets. For adapters, this class is used within the `WorkerRestClient` of `streampipes-connect-management`. In which cases did you experience the problem? Does this occur always or only for nested structures or something like that?

Thanks for your answer, I found the cause of the problem. It is in the guessSchema function that the secretValue is not decrypted. We can fix this problem in core. Please review my latest commit @dominikriemer

**Review by bossenti — APPROVED** [review]

**Pull request merged**
