### PR TITLE
feat: extend FileApi with the capability to query by the original file name

### PR DESCRIPTION
**Pull request by bossenti**
### Purpose

This PR extends the FileAPI of the core and the client to query by the original file name.

### Remarks

PR introduces (a) breaking change(s): no

PR introduces (a) deprecation(s): no

### CODE REVIEW

**Comment by bossenti** [comment]
Would you rather like to see the `IFileAPI` interface untouched and simply extend the file client with an additional method or are you fine with the proposed solution?

**Comment by tenthe** [comment]
Hey @bossenti,
I think it is ok to change the interface. But I would suggest to add a new method. Then it is not a breaking change for clients who already use the interface.
Further, I would suggest to rename the parameter of the existing methods to make clear that an internal id is used instead of the file name.

How can we deal with files that have the same name? Any ideas?

Cheers,
Philipp

**Comment by dominikriemer** [comment]
How do we distinguish between files with the same  original filename and which file will be delivered in this case? I think in this case we would need to ensure that no two files with the same filename can be uploaded.

**Comment by tenthe** [comment]
@dominikriemer yes, I totally agree. I think we should make sure that there are no two files with the same name.
Currently, if a user uploads two files with the same name and wants to delete one of them, it is not clear which one is which.
I think the best solution for this is to only allow unique names.
But I would address this in a separate issue and PR.

**Comment by bossenti** [comment]
I have simplified the API a bit so that we don't have the adapt all usages of `getFileContent`.
Let's take the uniqueness of uploaded files as a follow-up issue.

**Review by tenthe — APPROVED** [review]

**Pull request merged**
