### PR TITLE
Bump Kafka version to 3.x

### PR DESCRIPTION
**Pull request by dominikriemer**
### Purpose

Bump Kafka from 2.2 to 3.5 and enable KRaft mode without Zookeeper. 

### Remarks

PR introduces (a) breaking change(s): yes
The docker-compose file is updated which should be mentioned in the migration guide since it's not enough to simply bump the StreamPipes version in the env file.

PR introduces (a) deprecation(s): <yes/no>

### CODE REVIEW

**Review by tenthe — APPROVED** [review]

**Comment by bossenti** [comment]
Do we really want to drop support for Zookeeper directly?
Would be easier for existing deployments to still use zookeeper.

In addition:
> The docker-compose file is updated which should be mentioned in the migration guide since it's not enough to simply bump the StreamPipes version in the env file.

How would the migration look like?

**Comment by dominikriemer** [comment]
> Do we really want to drop support for Zookeeper directly? Would be easier for existing deployments to still use zookeeper.
> 

@bossenti What do you mean by existing deployments? Users using the bundled Kafka or users who provide their own Kafka infrastructure?

> In addition:
> 
> > The docker-compose file is updated which should be mentioned in the migration guide since it's not enough to simply bump the StreamPipes version in the env file.
> 
> How would the migration look like?

It's not really a migration, but users will need to either use the latest docker-compose file or copy the new environment variables from the docker compose file to their existing file.

**Comment by bossenti** [comment]
>or copy the new environment variables from the docker compose file to their existing file

Okay, so it is still possible to run StreamPipes with kafka and zookeeper if required?

**Review by RobertIndie — APPROVED** [review]

**Comment by RobertIndie** [comment]
> Okay, so it is still possible to run StreamPipes with kafka and zookeeper if required?

Yes, I think so.

**Pull request closed without merging**
